<?php

namespace Container406d25b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VajjpLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._VajjpL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._VajjpL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'victimRepository' => ['privates', 'App\\Repository\\VictimRepository', 'getVictimRepositoryService', true],
        ], [
            'victimRepository' => 'App\\Repository\\VictimRepository',
        ]);
    }
}
