<?php

namespace Container406d25b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOfferService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7IsKrbY.App\Entity\Offer' shared service.
     *
     * @return \App\Entity\Offer
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.7IsKrbY": it references class "App\\Entity\\Offer" but no such service exists.');
    }
}
