<?php

namespace Container406d25b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.P5cL_CR.App\Entity\Place' shared service.
     *
     * @return \App\Entity\Place
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.P5cL_CR": it references class "App\\Entity\\Place" but no such service exists.');
    }
}
