controllers_front:
    resource: ../../src/Controller/Front
    type: annotation

controllers_back:
    resource: ../../src/Controller/Back
    type: annotation
    prefix: /admin
    name_prefix: admin_


kernel:
    resource: ../../src/Kernel.php
    type: annotation
