<?php

namespace Container66PyMke;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlaceTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PlaceType' shared autowired service.
     *
     * @return \App\Form\PlaceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PlaceType.php';

        return $container->privates['App\\Form\\PlaceType'] = new \App\Form\PlaceType();
    }
}
