<?php

namespace Container66PyMke;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVictimService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.C4Ur_wD.App\Entity\Victim' shared service.
     *
     * @return \App\Entity\Victim
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.C4Ur_wD": it references class "App\\Entity\\Victim" but no such service exists.');
    }
}
