<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEJyMJ39\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEJyMJ39/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEJyMJ39.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEJyMJ39\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEJyMJ39\App_KernelDevDebugContainer([
    'container.build_hash' => 'EJyMJ39',
    'container.build_id' => 'ec21dc43',
    'container.build_time' => 1639389217,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEJyMJ39');
