<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBGc61it\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBGc61it/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBGc61it.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBGc61it\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBGc61it\App_KernelDevDebugContainer([
    'container.build_hash' => 'BGc61it',
    'container.build_id' => 'e6a60b86',
    'container.build_time' => 1639504202,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBGc61it');
