<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxnwapM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxnwapM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFxnwapM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFxnwapM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFxnwapM\App_KernelDevDebugContainer([
    'container.build_hash' => 'FxnwapM',
    'container.build_id' => 'cabae05a',
    'container.build_time' => 1644334348,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFxnwapM');
